services:
  db:
    image: mysql:8.0
    container_name: milk_db_dev
    env_file: 
      - ./.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_dev:/var/lib/mysql 
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev 
    container_name: milk_backend_dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: always

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev 
    container_name: milk_admin_dev
    ports:
      - "1002:1002"
    env_file:
      - ./.env.dev
    environment:
      DJANGO_SETTINGS_MODULE: Admin_M.settings
      DEBUG: ${DEBUG} 
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - ./admin:/app 
      - static_volume_dev:/app/static_collected
      - media_volume_dev:/app/media_collected 
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:1002"

volumes:
  db_data_dev: 
  static_volume_dev: 
  media_volume_dev: 
